movieproject/Movieapp/urls.py
from django.urls import path
from . import views

app_name = 'Movieapp'

urlpatterns = [
                path('', views.index, name='index'),
                path('register/', views.sign_up, name='sign_up'),
                path('sign_in/', views.sign_in, name='sign_in'),
                path('logout/', views.sign_out, name='sign_out'),
                path('movie/<int:movie_id>/', views.details, name='details'),
                path('add/', views.add_movie, name='add_movie'),
                path('update/<int:movie_id>/', views.update, name='update'),
                path('delete/<int:movie_id>/', views.delete, name='delete'),
                path('my-account/', views.my_account, name='my_account'),
                path('movies-added-by-user/', views.movies_added_by_user, name='movies_added_by_user'),
                path('genres/', views.genre_list, name='genre_list'),
                path('genres/<int:genre_id>/', views.genre_detail, name='genre_detail'),
                path('movies/year/<int:year>/', views.movies_by_year, name='movies_by_year'),
                path('top-rated/', views.top_imdb_rated, name='top_imdb_rated'),
                path('profile/edit/', views.profile_edit, name='profile_edit'),
                path('movie/<int:movie_id>/add_comment/', views.add_comment, name='add_comment'),
                path('filter_by_language/', views.filter_by_language, name='filter_by_language'),
 ]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Movieapp.urls', namespace='Movieapp')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/templates/add.html
            <h2>Add a New Movie</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Movie Title:</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="Enter movie title" value="{{ movie.title }}">
                </div> <br>
                <div class="form-group">
                    <label for="desc">Description:</label>
                    <textarea class="form-control" id="desc" name="desc" rows="3" placeholder="Enter the description">{{ movie.desc }}</textarea>
                </div><br>
                <div class="form-group">
                    <label for="release_date">Release Date:</label>
                    <input type="date" class="form-control" id="release_date" name="release_date" value="{{ movie.release_date }}">
                </div><br>
                <div class="form-group">
                    <label for="actors">Actors:</label>
                    <input type="text" class="form-control" id="actors" name="actors" placeholder="Enter actors" value="{{ movie.actors }}">
                </div><br>
                <div class="form-group">
                    <label for="category">Category:</label>
                    <input type="text" class="form-control" id="category" name="category" placeholder="Enter category" value="{{ movie.category }}">
                </div><br>
                <div class="form-group">
                    <label for="imdb_rating">IMDb Rating:</label>
                    <input type="number" class="form-control" id="imdb_rating" name="imdb_rating" step="0.1" placeholder="Enter IMDb rating" value="{{ movie.imdb_rating }}">
                    </div> <br>
                <div class="form-group">
                    <label for="language">Language:</label>
                    <select class="form-control" id="language" name="language">
                        <option value="malayalam">Malayalam</option>
                        <option value="hindi">Hindi</option>
                        <option value="english">English</option>
                    </select>
                </div> <br>
                <div class="form-group">
                    <label for="youtube_trailer_link">YouTube Trailer Link:</label>
                    <input type="url" class="form-control" id="youtube_trailer_link" name="youtube_trailer_link" placeholder="Enter YouTube trailer link" value="{{ movie.youtube_trailer_link }}">
                </div><br>
                <div class="form-group">
                    <label for="poster">Poster Image:</label>
                    <input type="file" class="form-control-file" id="poster" name="poster">
                </div><br>
                <button type="submit" class="btn btn-primary">Submit</button><br>

            <br>
            <a class="btn btn-secondary" href="{% url 'Movieapp:index' %}">Back to Home</a>
   </form>

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Movie project</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- Include jQuery -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <script src="https://kit.fontawesome.com/918de56c36.js" crossorigin="anonymous"></script>
</head>

<script>
    $(document).ready(function() {
        $('.dropdown-toggle').dropdown(); // Initialize Bootstrap dropdowns
    });
</script>



<body style="background-color: #b3b3b3">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'Movieapp:index' %}">Movie Hub</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <!-- Only show these links if the user is authenticated -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Movieapp:sign_out' %}">Sign Out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Movieapp:my_account' %}">My Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Movieapp:movies_added_by_user' %}">Movies Added by You</a>
                </li>

            {% else %}
                <!-- Show these links if the user is not authenticated -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Movieapp:sign_up' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Movieapp:sign_in' %}">Sign In</a>
                </li>
            {% endif %}
            <!-- Always show the Genre link -->
<!--            <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          Genre-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--          {% for genre in genres %}-->
<!--          <a class="dropdown-item" href="{% url 'genre_detail' genre.id %}">{{ genre.name }}</a>-->
<!--          {% endfor %}-->
<!--        </div>-->
<!--      </li>-->
            <!-- More dropdown menu -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Language
                </a>
                <div class="dropdown-menu" aria-labelledby="languageDropdown">
                    <a class="dropdown-item" href="{% url 'Movieapp:filter_by_language' %}?language=malayalam">Malayalam</a>
                    <a class="dropdown-item" href="{% url 'Movieapp:filter_by_language' %}?language=hindi">Hindi</a>
                    <a class="dropdown-item" href="{% url 'Movieapp:filter_by_language' %}?language=english">English</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    More
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'Movieapp:movies_by_year' 2024 %}">Movies Released in 2024</a>
                    <a class="dropdown-item" href="{% url 'Movieapp:movies_by_year' 2023 %}">Movies Released in 2023</a>
                    <a class="dropdown-item" href="{% url 'Movieapp:movies_by_year' 2022 %}">Movies Released in 2022</a>
                    <a class="dropdown-item" href="{% url 'Movieapp:top_imdb_rated' %}">Top User Rated Movies</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'Movieapp:add_movie' %}">Add Movie</a>
                    {% if user.is_authenticated %}
                        <!-- Show logout link if user is authenticated -->
                        <a class="dropdown-item" href="{% url 'Movieapp:sign_out' %}">Logout</a>
                    {% endif %}
                </div>
            </li>
        </ul>
    </div>
</nav>


<div class="container">
    <div>
        {% block content %}
        {% block body %}
        {% endblock %}
        {% endblock %}
    </div>

</div>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $('.dropdown-toggle').dropdown();
    });
</script>
</body>
</html>

movieproject/templates/delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete this movie?</p>
    <input type="submit" value="Delete">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ movie.poster.url }}" width="50%" height="auto" style="object-fit: cover; margin-right: 20px;">
        </div>
        <div class="col-md-6">
            <h2>{{ movie.title }}</h2>
            <hr>
            <h5>{{ movie.desc }}</h5>
            <br>
            <h4>{{ movie.release_date }}</h4>
            <br>
            <h4>Actors: {{ movie.actors }}</h4>
<!--            <h4>Category: {{ movie.category }}</h4>-->
             <h4>Category: {{ movie.category }}</h4><br>
            <h4>Rating: {{ movie.imdb_rating }}</h4>
            <h4>YouTube Trailer: <a href="{{ movie.youtube_trailer_link}}">{{ movie.youtube_trailer_link }}</a></h4>
            {% if user.is_authenticated and user == movie.creator %}
            <a class="btn btn-warning" href="{% url 'Movieapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'Movieapp:delete' movie.id %}">Delete</a>
            {% endif %}


            <a class="btn btn-primary" href="{% url 'Movieapp:index' %}">Back to Home</a>

            <h3>Add a Comment</h3>
        <form method="post" action="{% url 'Movieapp:add_comment' movie.id %}">
            {% csrf_token %}
                <textarea name="comment" rows="3" cols="40"></textarea><br>
                <button type="submit" class="btn btn-primary">Add Comment</button>
        </form>
            <!-- Display Comments -->
            <h3>Comments</h3>
                <ul>
                    {% for comment in comments %}
                    <li>{{ comment.content }}</li>
                    {% endfor %}
                </ul>





            <!--        comment form-->
<!--              <h3>Comments</h3>-->
<!--            <form method="post" action="{% url 'Movieapp:add_comment' movie.id %}">-->
<!--                {% csrf_token %}-->
<!--                <textarea name="comment" rows="3" cols="40"></textarea><br>-->
<!--                <a class="btn btn-warning" href="{% url 'Movieapp:details' movie.id %}">Add Comment</a>-->
<!--&lt;!&ndash;                <button type="submit" class="btn btn-primary">Add Comment</button>&ndash;&gt;-->
<!--            </form>-->

<!--            &lt;!&ndash; Display Comments &ndash;&gt;-->
<!--            <h3>Comments</h3>-->
<!--            <ul>-->
<!--                {% for comment in comments %}-->
<!--                    <li>{{ comment.content }}</li>-->
<!--                {% endfor %}-->
<!--            </ul>-->
        </div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<form method = 'POST' enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit">
</form>

movieproject/templates/genre_detail.html
<h1>{{ genre.name }}</h1>
    <h2>Movies in {{ genre.name }}</h2>
    <ul>
        {% for movie in movies %}
            <li>{{ movie.title }}</li>
        {% endfor %}
    </ul>

movieproject/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block body %}

<!--    <h1>Welcome to the Movie Hub </h1>-->

    {% if user.is_authenticated %}
        <!-- If user is authenticated, display user's name and logout link -->
        <p>Welcome, {{ user.username }}!</p>
<!--        <a href="{% url 'Movieapp:sign_out' %}">Logout</a>-->
    {% else %}
<!--        &lt;!&ndash; If user is not authenticated, display sign up and sign in links &ndash;&gt;-->
<!--        <a href="{% url 'Movieapp:sign_up' %}">Sign Up</a><br>-->
<!--        <a href="{% url 'Movieapp:sign_in' %}">Sign In</a>-->
    {% endif %}

    <!-- Display movies added by the current user -->
    <h4>Movie Hub is a place where you can add all your favourite movies and its details.Try now....</h4><br>

<!--   index page style                -->

<div class="container">
    <div class="row">
        {% for i in movie_list %}
            <div class="col-md-3 mb-3">
                <div class="card" style="width: 16rem; border: 1px solid #ccc;">
                    <img class="card-img-top" src="{{ i.poster.url }}" alt="Card image cap" style="height: 200px;">
                    <div class="card-body">
                        <h5 class="card-title" style="color: #333;">{{ i.title }}</h5>
                        <p class="card-text" style="max-height: 80px; overflow: hidden; color: #666;">{{ i.desc }}</p>
                        <a href="{% url 'Movieapp:details' i.id %}" class="btn btn-primary" style="background-color: #007bff; border-color: #007bff;">Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

movieproject/templates/movies_by_year.html
{% extends 'base.html' %}

{% block content %}
  <h1>Movies Released in {{ year }}</h1>
  <ul>
    {% for movie in movies %}
      <li>
        <a href="{% url 'Movieapp:details' movie.id %}">{{ movie.title }}</a> ({{ movie.release_date|date:"Y" }})
      </li>
    {% endfor %}
  </ul>
{% endblock %}

movieproject/templates/movies_listing.html
<!-- movies_listing.html -->
{% extends 'base.html' %}

{% block content %}
    <h1>Movies Listing</h1>

<!--    &lt;!&ndash; Filter form &ndash;&gt;-->
<!--    <form method="GET" action="{% url 'Movieapp:filter_by_language' %}">-->
<!--        <label for="language">Filter by Language:</label>-->
<!--        <select id="language" name="language">-->
<!--            <option value="">All</option>-->
<!--            <option value="malayalam">Malayalam</option>-->
<!--            <option value="hindi">Hindi</option>-->
<!--            <option value="english">English</option>-->
<!--        </select>-->
<!--        <button type="submit">Apply Filter</button>-->
<!--    </form>-->

    <!-- Display filtered movies -->
<ul>
    {% for movie in filtered_movies %}
        <li>
            <a href="{% url 'Movieapp:details' movie.id %}">{{ movie.title }}</a> - {{ movie.language }}
        </li>
    {% endfor %}
</ul>

<!--    <ul>-->
<!--        {% for movie in filtered_movies %}-->
<!--            <li>{{ movie.title }} - {{ movie.language }}</li>-->
<!--        {% endfor %}-->
<!--    </ul>-->
{% endblock %}

movieproject/templates/my_account.html
<h1>Welcome, {{ user.username }}</h1>
    <h2>User Information</h2>
    <p>Email: {{ user.email }}</p>
    <p>First Name: {{ user.first_name }}</p>
    <p>Last Name: {{ user.last_name }}</p>

<!--    <h1>Movies Added by You</h1>-->
<!--    <ul>-->
<!--        {% for movie in user_movies %}-->
<!--            <li>-->
<!--               <h2><strong>Title:</strong> {{ movie.title }} <br></h2>-->
<!--                <strong>Description:</strong> {{ movie.desc }} <br>-->
<!--                <strong>Release Date:</strong> {{ movie.release_date }} <br>-->
<!--                &lt;!&ndash; Add more details as needed &ndash;&gt;-->
<!--            </li>-->
<!--        {% empty %}-->
<!--            <li>No movies added by you yet.</li>-->
<!--        {% endfor %}-->
<!--    </ul>-->

    <!-- Add more details as needed -->
<!--    <a href="{% url 'Movieapp:add_movie' %}">Add Movie</a><br><br>-->

    <a href="{% url 'Movieapp:profile_edit' %}">Edit Profile</a>

movieproject/templates/profile.html
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save Changes</button>
</form>

movieproject/templates/register.html
<h1>Sign Up</h1>
<!--    {% if welcome_message %}-->
<!--        <p>{{ welcome_message }}</p>-->
<!--    {% endif %}-->
<form method="POST" novalidate>
	{% csrf_token %}


	{% for field in form %}
	<p>
		{% if field.errors %}
		<ul class="errorlist">
			{% for error in field.errors %}
			<li>{{ error }}</li>
			{% endfor %}
		</ul>
		{% endif %}
	 	{{ field.label_tag }} {{ field }}
	</p>
	{% endfor %}
	<input type="submit" value="Register" />
</form>

movieproject/templates/top_imdb_rated_movies.html
<!-- top_imdb_rated_movies.html -->
{% extends 'base.html' %}

{% block content %}
  <h1>Top User Rated Movies</h1>
  <ul>
    {% for movie in top_rated_movies %}
      <li>
        <a href="{% url 'Movieapp:details' movie.id %}">{{ movie.title }}</a> - {{ movie.imdb_rating }}
      </li>
    {% endfor %}
  </ul>
{% endblock %}

movieproject/templates/welcome_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to our website!</title>
</head>
<body>
    <h2>Welcome {{ user.first_name }}!</h2>
    <p>Thank you for registering on our website. We are excited to have you as a member!</p>
    <!-- Add any additional content or instructions here -->
</body>
</html>